#!/bin/sh
if [ -n "$PUSH_REMOTE" ]; then
	if [ "$VCS" = git ] && [ -d .git ]; then
		git push "$PUSH_REMOTE" "${PUSH_BRANCH:-master}" || true
	else
		echo "PUSH_REMOTE not yet supported for $VCS" >&2
	fi
fi
